//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhmDome.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OhmDome.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;OhmDomeDB&gt;
        ///  &lt;Band&gt;
        ///    &lt;ColorCode Color=&quot;Black&quot;&gt;
        ///      0
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Brown&quot;&gt;
        ///      1
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Red&quot;&gt;
        ///      2
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Orange&quot;&gt;
        ///      3
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Yellow&quot;&gt;
        ///      4
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Green&quot;&gt;
        ///      5
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Blue&quot;&gt;
        ///      6
        ///    &lt;/ColorCode&gt;
        ///    &lt;ColorCode Color=&quot;Violet&quot;&gt;
        ///      7
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OhmDomeDB {
            get {
                return ResourceManager.GetString("OhmDomeDB", resourceCulture);
            }
        }
    }
}
